config/routes.rb
Rails.application.routes.draw do

  resources :comments
  devise_for :users, controller: {
      session: 'users/session'
  }

  root 'pages#home'
  get 'about'     => 'pages#about'
  get 'contact'   => 'pages#contact'
  get 'posts/:id' => 'posts#show', as: :post
  get 'categories/:id' => 'categories#show', as: :category

  namespace :admin do
    resources   :users
    resources   :posts
    resources   :categories
  end

  scope :admin do
    root 'admin#dashboard', as: :admin
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  mount_uploader :featured_image, FileUploader
  has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :featured_image, FileUploader
  paginates_per 20
  belongs_to :user
  belongs_to :category
  has_many  :comments

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :posts
  has_many :comments

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all.page params[:page]
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:success] = "Post successfully created"
      redirect_to admin_post_path(@post)
    else
      flash[:error] = "Create failed"
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post successfully updated"
      redirect_to admin_post_path(@post)
    else
      flash[:error] = "Update failed"
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post successfully deleted"
    redirect_to admin_posts_path
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end
  def post_params
    params.require(:post).permit(:name, :content, :featured_image, :category_id)
  end
  def set_category
    @category = Category.find(params[:category_id])
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_admin!

  def dashboard
    @users = User.all
    @posts = Post.all
    @comments = Comment.all
  end

  private
  def authenticate_admin!
    return redirect_to new_user_session_path unless current_user
    sign_out(current_user) && (redirect_to new_user_session_path) unless current_user.has_role? :admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    if resource.has_role? :admin
      admin_path
    else
      super
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @posts = Post.where(category_id: @category.id).page params[:page]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    if @comment.save
      render partial: 'comments/comment',
             locals: {comment: @comment},
             status: :created
    end

  end

  private
  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Post.all.page params[:page]
  end

  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])

    @comments = @post.comments
    @new_comment = Comment.new
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby Vietnam"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/admin/dashboard.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Dashboard</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-green">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-edit fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= @posts.size %></div>
            <br>
            <div>Posts</div>
          </div>
        </div>
      </div>
      <%= link_to admin_posts_path, data: {no_turbolink: true} do %>
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-user fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= @users.size %></div>
            <br>
            <div><%= (@users.size > 1) ? 'Users':'User' %></div>
          </div>
        </div>
      </div>
      <%= link_to admin_users_path, data: {no_turbolink: true} do %>
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-yellow">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-comment fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= @comments.size %></div>
            <br>
            <div>Comments</div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-red">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-support fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge">0</div>
            <br>
            <div>Contact</div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
</div>
<!-- /.row -->

app/views/admin/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Admin Panel", admin_path, class: "navbar-brand", data: {no_turbolink: true} %>
  </div>
  <!-- /.navbar-header -->

  <ul class="nav navbar-top-links navbar-right">
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-user">
        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
        </li>
        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to '<i class="fa fa-sign-out fa-fw"></i> Sign Out'.html_safe, destroy_user_session_path, method: :delete, data: { no_turbolink: true } %>
        </li>
      </ul>
      <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
  </ul>
  <!-- /.navbar-top-links -->

  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
        <li class="sidebar-search">
          <div class="input-group custom-search-form">
            <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
          </div>
          <!-- /input-group -->
        </li>
        <li>
          <%= link_to '<i class="fa fa-dashboard fa-fw"></i> Dashboard</a>'.html_safe, admin_path, data: {no_turbolink: true} %>
        </li>
        <li>
          <%= link_to '<i class="fa fa-edit fa-fw"></i> Posts<span class="fa arrow">'.html_safe, "#", data: {no_turbolink: true} %>
          <ul class="nav nav-second-level">
            <li>
              <%= link_to "All Posts", admin_posts_path, data: {no_turbolink: true} %>
            </li>
            <li>
              <%= link_to "New Post", new_admin_post_path, data: {no_turbolink: true} %>
            </li>
            <li>
              <%= link_to "Categoty", admin_categories_path, data: {no_turbolink: true} %>
            </li>
          </ul>
        </li>
        <li>
          <%= link_to '<i class="fa fa-user fa-fw"></i> Users<span class="fa arrow"></span>'.html_safe, "#", data: {no_turbolink: true} %>
          <ul class="nav nav-second-level">
            <li>
              <%= link_to 'All Users', admin_users_path , data: {no_turbolink: true} %>
            </li>
            <li>
              <a href="#">New User</a>
            </li>
            <li>
              <a href="#">Role</a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /.sidebar-collapse -->
  </div>
  <!-- /.navbar-static-side -->
</nav>

app/views/layouts/_fb_script.html.erb
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '595313330629835',
      xfbml      : true,
      version    : 'v2.6'
    });
  };

  (function(d, s, id){
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <ul class="list-inline text-center">
          <li>
            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
            </a>
          </li>
          <li>
            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
            </a>
          </li>
          <li>
            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
            </a>
          </li>
        </ul>
        <p class="copyright text-muted">Copyright &copy;2016 Ruby-vn.com</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('<%= yield(:featured_image).nil? ? asset_path('home-bg.jpg'):asset_path(yield(:featured_image)) %>')">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <h1>
            <%= yield(:name).nil? ? "Ruby Blog":yield(:name) %>
          </h1>
          <hr class="small">
          <span class="subheading"><%= yield(:description).nil? ? "A Ruby Blog on Vietnam":yield(:description) %></span>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-flash alert-<%= message_type %>">
    <% if message.kind_of?(Array) %>
      <% message.each do |msg| %>
        <%= msg %>
        <%= raw("<br/>") unless msg == message.last %>
      <% end %>
    <% else %>
      <%= message %>
    <% end %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Ruby-vn", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <% Category.all.each do |category| %>
            <li>
              <%= link_to category.name, category_path(category) %>
            </li>
        <% end %>
        <li>
          <%= link_to "About", about_path %>
        </li>
        <li>
          <%= link_to "Contact", contact_path %>
        </li>
        <li>
          <% if user_signed_in? %>
              <%= link_to "Logout", destroy_user_session_path, method: :DELETE %>
          <% else %>
              <%= link_to "Log in", new_user_session_path %>
          <% end %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/_shim.html.erb
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Ruby Vietnam</title>

  <%= stylesheet_link_tag    'admin/admin', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin/admin', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= render('layouts/shim') %>
</head>

<body>
<div id="wrapper">

  <%= render ('admin/shared/navbar')%>
  <div id="page-wrapper">
    <%= render('layouts/message') %>
    <%= yield %>
    <%= render('admin/shared/footer') %>
  </div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="vi">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title><%= full_title(yield(:name)) %></title>

  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= render('layouts/shim') %>
</head>
<body>
<%= render('layouts/fb_script') %>
<%= render('layouts/nav') %>
<%= render('layouts/header') %>
<div class="container">
  <%= yield %>
</div>
<hr>
<%= render('layouts/footer') %>
</body>
</html>

app/views/layouts/footer.html.erb
<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <ul class="list-inline text-center">
          <li>
            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
            </a>
          </li>
          <li>
            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
            </a>
          </li>
          <li>
            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
            </a>
          </li>
        </ul>
        <p class="copyright text-muted">Copyright &copy;2016 Ruby-vn.com</p>
      </div>
    </div>
  </div>
</footer>